# Generated by Django 4.2.8 on 2023-12-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("F", "First Player to Move"),
                    ("S", "Second Player to Move"),
                    ("W", "First Player Wins"),
                    ("L", "Second Player Wins"),
                    ("D", "Draw"),
                ],
                default="F",
                max_length=1,
            ),
        ),
    ]
